#pragma once

#define KEYBOARD_0 SDL_SCANCODE_0
#define KEYBOARD_1 SDL_SCANCODE_1
#define KEYBOARD_2 SDL_SCANCODE_2
#define KEYBOARD_3 SDL_SCANCODE_3
#define KEYBOARD_4 SDL_SCANCODE_4
#define KEYBOARD_5 SDL_SCANCODE_5
#define KEYBOARD_6 SDL_SCANCODE_6
#define KEYBOARD_7 SDL_SCANCODE_7
#define KEYBOARD_8 SDL_SCANCODE_8
#define KEYBOARD_9 SDL_SCANCODE_9

#define KEYBOARD_A SDL_SCANCODE_A
#define KEYBOARD_B SDL_SCANCODE_B
#define KEYBOARD_C SDL_SCANCODE_C
#define KEYBOARD_D SDL_SCANCODE_D
#define KEYBOARD_E SDL_SCANCODE_E
#define KEYBOARD_F SDL_SCANCODE_F
#define KEYBOARD_G SDL_SCANCODE_G
#define KEYBOARD_H SDL_SCANCODE_H
#define KEYBOARD_I SDL_SCANCODE_I
#define KEYBOARD_J SDL_SCANCODE_J
#define KEYBOARD_K SDL_SCANCODE_K
#define KEYBOARD_L SDL_SCANCODE_L
#define KEYBOARD_M SDL_SCANCODE_M
#define KEYBOARD_N SDL_SCANCODE_N
#define KEYBOARD_O SDL_SCANCODE_O
#define KEYBOARD_P SDL_SCANCODE_P
#define KEYBOARD_Q SDL_SCANCODE_Q
#define KEYBOARD_R SDL_SCANCODE_R
#define KEYBOARD_S SDL_SCANCODE_S
#define KEYBOARD_T SDL_SCANCODE_T
#define KEYBOARD_U SDL_SCANCODE_U
#define KEYBOARD_V SDL_SCANCODE_V
#define KEYBOARD_W SDL_SCANCODE_W
#define KEYBOARD_X SDL_SCANCODE_X
#define KEYBOARD_Y SDL_SCANCODE_Y
#define KEYBOARD_Z SDL_SCANCODE_Z

#define KEYBOARD_UP SDL_SCANCODE_UP
#define KEYBOARD_DOWN SDL_SCANCODE_DOWN
#define KEYBOARD_LEFT SDL_SCANCODE_LEFT
#define KEYBOARD_RIGHT SDL_SCANCODE_RIGHT